module.exports = {
    toggle: function() {
        // THIS VARIABLE CONTROLS CONSOLE LOGGING THROUGHOUT THE PROGRAM - IT IS MEANT FOR STAGING AND TESTING ONLY - DO NOT LEAVE ON IN PRODUCTION!
        var ENABLE_VERBOSE_LOGGING = true;
        return ENABLE_VERBOSE_LOGGING;
    }
}